package pratice;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Iterator;
import java.util.Properties;
import java.util.Random;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import com.crm.sharphawk.PomRepository.LoginPage;
import com.crm.sharphawk.genericutility.ExcelUtility;
import com.crm.sharphawk.genericutility.FileUtility;
import com.crm.sharphawk.genericutility.JavaUtility;
import com.crm.sharphawk.genericutility.WebDriverUtility;
public class CreatePurchaseOrderWithVendorNameTest 
{
	public static void main(String[] args) throws Throwable 
	{
		FileUtility fLib=new FileUtility();
		ExcelUtility eLib=new ExcelUtility();
		JavaUtility jLib=new JavaUtility();
		WebDriverUtility wLib=new WebDriverUtility();
		String Url=fLib.getPropertyData("url");
		String uName=fLib.getPropertyData("username");
		String pWord=fLib.getPropertyData("password");
		WebDriver driver=new ChromeDriver();
		wLib.waitForElementInDOM(driver);
		driver.get(Url);
		driver.manage().window().maximize();
		LoginPage lp=new LoginPage(driver);
		lp.LoginToVtiger(Url,uName,pWord);
//		driver.findElement(By.xpath("//input[@name='user_name']")).sendKeys(uName);
//		driver.findElement(By.xpath("//input[@name='user_password']")).sendKeys(pWord);
//		driver.findElement(By.xpath("//input[@id='submitButton']")).click();
		WebElement more = driver.findElement(By.xpath("//a[text()='More']"));	
		wLib.mouseOverOnElement(driver,more);
		driver.findElement(By.name("Vendors")).click();
		driver.findElement(By.xpath("//img[@title='Create Vendor...']")).click();
		int r1=jLib.getRandomNUm();
		String vendor = eLib.getDataFromExcel("vtiger",1,7);
		driver.findElement(By.className("detailedViewTextBox")).sendKeys(vendor+r1);
		driver.findElement(By.xpath("(//input[@class='crmbutton small save'])[1]")).click();
		WebElement more1 = driver.findElement(By.xpath("//a[text()='More']"));	
		wLib.mouseOverOnElement(driver,more1);
		driver.findElement(By.name("Purchase Order")).click();
		driver.findElement(By.xpath("//img[@title='Create Purchase Order...']")).click();
		String pTitle = driver.getWindowHandle();
		eLib.setDataToExcel("vtiger", 1, 6, pTitle);
		String subject = eLib.getDataFromExcel("vtiger",1,5);
		driver.findElement(By.name("subject")).sendKeys(subject+r1);
		driver.findElement(By.xpath("(//img[@title='Select'])[1]")).click();		
		wLib.swithToWindow(driver,pTitle);		
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@name='search_text']")).sendKeys(eLib.getDataFromExcel("vtiger",1,7)+r1);
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@class='crmbutton small create']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//a[@class='listFormHeaderLinks']/../../..//a[@id='1']")).click();	
		Thread.sleep(3000);
		wLib.swithToWindow(driver,pTitle);
		String addressA = eLib.getDataFromExcel("vtiger",1,8);
		String addressB = eLib.getDataFromExcel("vtiger",1,9);
		driver.findElement(By.xpath("(//textarea[@class='detailedViewTextBox'])[1]")).sendKeys(addressA);
		driver.findElement(By.xpath(" //textarea[@name='ship_street']")).sendKeys(addressB);
		driver.findElement(By.xpath(" //img[@id='searchIcon1']")).click();
		wLib.swithToWindow(driver,pTitle);	
		String abc = eLib.getDataFromExcel("vtiger",1,3);
		driver.findElement(By.xpath("//input[@class='txtBox']")).sendKeys(abc);
		driver.findElement(By.xpath("//input[@class='crmbutton small create']")).click();
		driver.findElement(By.xpath("//a[@class='listFormHeaderLinks']/../../..//a[@id='popup_product_32']")).click();
		wLib.swithToWindow(driver,pTitle);
		String qty=eLib.getDataFromExcelFormatter("vtiger", 1, 10);
	    driver.findElement(By.xpath("//input[@id='qty1']")).sendKeys(qty);
		//driver.findElement(By.xpath("//input[@id='qty1']")).sendKeys("1");
		driver.findElement(By.xpath("(//input[@class='crmbutton small save'])[1]")).click();
		WebElement signout = driver.findElement(By.xpath("//img[@src='themes/softed/images/user.PNG']"));
		wLib.mouseOverOnElement(driver, signout);
		driver.findElement(By.xpath("//a[text()='Sign Out']")).click();
		driver.close();
	}
}
